"""init

Revision ID: 808f53c325b5
Revises: 
Create Date: 2026-08-26 11:47:57.713980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # нужен для типа Vector (knowledge_chunks.embedding) —
                             # Alembic autogenerate не добавляет этот импорт сам


# revision identifiers, used by Alembic.
revision: str = '808f53c325b5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('member_id', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=False),
    sa.Column('application_token', sa.String(), nullable=False),
    sa.Column('enabled_modules', sa.JSON(), nullable=False),
    sa.Column('bot_ids', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('member_id'),
    sa.UniqueConstraint('domain')
    )
    op.create_table('knowledge_chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('member_id', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source_type in ('catalog', 'kb')", name='ck_knowledge_chunks_source_type'),
    sa.ForeignKeyConstraint(['member_id'], ['clients.member_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ux_knowledge_chunks_source', 'knowledge_chunks', ['member_id', 'source_type', 'source_id'], unique=True)
    op.create_table('test_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('current_score', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('questions_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status in ('active', 'completed')", name='ck_test_sessions_status'),
    sa.ForeignKeyConstraint(['domain'], ['clients.domain'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ux_test_sessions_active_per_user', 'test_sessions', ['domain', 'user_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_test_sessions_active_per_user', table_name='test_sessions', postgresql_where=sa.text("status = 'active'"))
    op.drop_table('test_sessions')
    op.drop_index('ux_knowledge_chunks_source', table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    op.drop_table('clients')
    # ### end Alembic commands ###
